# Generated by Django 5.2.6 on 2025-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip_alter_requestlog_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='coutry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
