# Generated by Django 5.2.6 on 2025-09-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0004_suspiciousip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name': 'Blocked IP', 'verbose_name_plural': 'Blocked IPs'},
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Request Log', 'verbose_name_plural': 'Request Logs'},
        ),
        migrations.AlterModelOptions(
            name='suspiciousip',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Suspicious IP', 'verbose_name_plural': 'Suspicious IPs'},
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='coutry',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, help_text='Country resolved from the IP address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IP address blocked from accessing the application', unique=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, help_text='City resolved from the IP address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Client IP address'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.CharField(help_text='Path requested by the client (e.g., /login)', max_length=200),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(help_text='Date and time when the request was logged'),
        ),
        migrations.AlterField(
            model_name='suspiciousip',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when suspicious behavior was detected'),
        ),
        migrations.AlterField(
            model_name='suspiciousip',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Suspicious IP address flagged by anomaly detection'),
        ),
        migrations.AlterField(
            model_name='suspiciousip',
            name='reason',
            field=models.TextField(help_text='Reason this IP was flagged (e.g., >100 requests/hour)'),
        ),
    ]
